In [2]:
import numpy as np

In [41]:
"f(x)= a+ 2b+ 3c+ 4d- 30"
# initialization
n=6 # number of chromosome
epoch=0
chromosome=np.random.randint(0,30,(n,4))


In [42]:
chromosome

array([[19, 15, 16, 18],
       [25,  1,  5,  2],
       [ 4,  2,  3, 13],
       [17, 13, 22,  9],
       [24,  8, 22, 14],
       [ 6, 16, 10,  5]])

In [43]:
chromosome[:,0]

array([19, 25,  4, 17, 24,  6])

In [44]:
# computation of fitness function 
    
objective= abs(30 - chromosome[:,0]-2*chromosome[:,1]
               -3*chromosome[:,2]-4*chromosome[:,3])
print("Fitness object :" , objective)


Fitness object : [139  20  39 115 132  58]


In [45]:
# selection of fittest chromosme
fitness= 1/ (1+objective)
print("Fitness :", fitness)

Fitness : [ 0.00714286  0.04761905  0.025       0.00862069  0.0075188   0.01694915]


In [46]:
# calculating the total of fitness function 
total=fitness.sum()
print("Total :", total)

Total : 0.112850543952


In [47]:
# calculationg Probability for each chromosome
prob=fitness/ total
print("Probability :",prob)

Probability : [ 0.06329484  0.4219656   0.22153194  0.07639032  0.06662615  0.15019115]


In [48]:
#Selection using Roulette Wheel and Calculating cumulative probability
cum_sum= np.cumsum(prob)
print("Cumulative Sum :",cum_sum)

Cumulative Sum : [ 0.06329484  0.48526044  0.70679238  0.78318271  0.84980885  1.        ]


In [49]:
# Genertaing Random Numbers in the range 0-1
print(chromosome.shape[0]) # => n
R=np.random.random((chromosome.shape[0]))
print("Random Number : ",R)
print(R.shape[0])

6
Random Number :  [ 0.37023063  0.85219164  0.68936189  0.50293123  0.15052767  0.86549708]
6


In [50]:
# making a new matrix of chromosome for calculation purpose
chromosome_2=np.zeros((chromosome.shape[0],4))
for i in range(R.shape[0]):
    for j in range(chromosome.shape[0]):
        if(R[i]< cum_sum[j]):
            chromosome_2[i,:]=chromosome[j,:]
            break
    
chromosome=chromosome_2
print(chromosome)

[[ 25.   1.   5.   2.]
 [  6.  16.  10.   5.]
 [  4.   2.   3.  13.]
 [  4.   2.   3.  13.]
 [ 25.   1.   5.   2.]
 [  6.  16.  10.   5.]]


In [51]:
# crossover
R=np.random.random((chromosome.shape[0]))
print("Random values :",R)

Random values : [ 0.7397575   0.74232713  0.82308624  0.89886048  0.15883648  0.07354287]


In [52]:
# cross over rate 
pc=0.25
flag =R<pc
print(flag)

[False False False False  True  True]


In [53]:
# Determining the cross chromosme
cross_chromosome= chromosome[[(i==True) for i in flag]]
print("cross chromosome :",cross_chromosome)
len_cross_chromosome= len(cross_chromosome)
print(len_cross_chromosome)

cross chromosome : [[ 25.   1.   5.   2.]
 [  6.  16.  10.   5.]]
2


In [54]:
# calculating cross values
cross_value=np.random.randint(1,3,len_cross_chromosome)
print("Cross Values : ",cross_value)


Cross Values :  [1 2]


In [55]:
# performing cross-over


# copying the chromosme values for calculations
cpy_chromosome=np.zeros(cross_chromosome.shape)
for i in range(cross_chromosome.shape[0]):
    cpy_chromosome[i,:]=cross_chromosome[i,:]

print(cpy_chromosome)

[[ 25.   1.   5.   2.]
 [  6.  16.  10.   5.]]


In [57]:
if(len_cross_chromosome>1):
    for i in range(len_cross_chromosome):
        c_val=cross_value[i]
        if(i==len_cross_chromosome-1):
            cross_chromosome[i,c_val:]=cpy_chromosome[0,c_val:]
        else:
            cross_chromosome[i,c_val:]=cpy_chromosome[i+1,c_val:]
    
print("Cross-Overed Chromosome :", cross_chromosome)


Cross-Overed Chromosome : [[ 25.  16.  10.   5.]
 [  6.  16.   5.   2.]]


In [58]:
i=0 # index chromosome
j=0 # 
for x in flag:
    if(x):
        chromosome[i,:]=cross_chromosome[j,:]
        j+=1
    i+=1
print("New Chromosomes :",chromosome)


New Chromosomes : [[ 25.   1.   5.   2.]
 [  6.  16.  10.   5.]
 [  4.   2.   3.  13.]
 [  4.   2.   3.  13.]
 [ 25.  16.  10.   5.]
 [  6.  16.   5.   2.]]


In [60]:
#calculating the total number of generations
a,b= chromosome.shape[0],chromosome.shape[1]
total_gen=a*b
print("Total Generations :",total_gen)

Total Generations : 24


In [61]:
#mutation rate => pm
pm=0.1
no_of_mutations =int(np.round(pm*total_gen))
print("No of Mutations : ",no_of_mutations)

No of Mutations :  2


In [64]:
#calculating the Generation number
gen_num=np.random.randint(0,total_gen-1,no_of_mutations)
print("Generated Random Numbers : ",gen_num)

Generated Random Numbers :  [10  1]


In [65]:
# Genertaing a random number which can replace the selected chromosome to be mutated
Replacing_num = np.random.randint(0,30,no_of_mutations)
print("Numbers to be replaced : ",Replacing_num)

Numbers to be replaced :  [19 19]


In [67]:
for i in range(no_of_mutations):
    a=gen_num[i]
    row=a//4
    col=a%4
    chromosome[row,col]=Replacing_num[i]
    
print("Chromosome after Mutation : ",chromosome)

Chromosome after Mutation :  [[ 25.  19.   5.   2.]
 [  6.  16.  10.   5.]
 [  4.   2.  19.  13.]
 [  4.   2.   3.  13.]
 [ 25.  16.  10.   5.]
 [  6.  16.   5.   2.]]


In [68]:
# Genetic algorithm

In [96]:
import numpy as np
n=6
epoch=0
chromosome= np.random.randint(0,30,(n,4))
print("Chromosome : ",chromosome)

while(epoch<200):
    objective= abs(30- chromosome[:,0]- chromosome[:,1]*2 -chromosome[:,2]*3-chromosome[:,3] )
    print("Fitness Object :",objective)

    fitness=1 / ( 1+ objective)
    print("Fitness : ",fitness)

    total= fitness.sum()
    print("Total ",total)

    prob=fitness/total
    print("Probability : ",prob)

    cumsum=np.cumsum(prob)
    print("Cumulative Probability : ",cumsum)

    R=np.random.random((chromosome.shape[0]))
    print("Random Numbers : ",R)

    temp_chromosome=np.zeros((chromosome.shape))

    for i in range(R.shape[0]):
        for j in range(chromosome.shape[0]):
            if(R[i] < cumsum[j]):
                temp_chromosome[i,:]=chromosome[j,:]
                break
    print(temp_chromosome)
    
    chromosome=temp_chromosome
    print("Updated chromosome : ",chromosome)
    
    R=np.random.random((chromosome.shape[0]))
    pc=0.25 
    flag= R< pc
    print(flag)
    
    cross_chromosome= chromosome[[(i==True) for i in flag]]
    print("cross chromosome :",cross_chromosome)
    len_cross_chromosome= len(cross_chromosome)
    print(len_cross_chromosome)
    
    # calculating cross values
    cross_value=np.random.randint(1,3,len_cross_chromosome)
    print("Cross Values : ",cross_value)
    
    # performing cross-over


    # copying the chromosme values for calculations
    temp_chromosome=np.zeros(cross_chromosome.shape)
    for i in range(cross_chromosome.shape[0]):
        temp_chromosome[i,:]=cross_chromosome[i,:]

    print(temp_chromosome)
    
    if(len_cross_chromosome>1):
        for i in range(len_cross_chromosome):
            c_val=cross_value[i]
            if(i==len_cross_chromosome-1):
                cross_chromosome[i,c_val:]=temp_chromosome[0,c_val:]
            else:
                cross_chromosome[i,c_val:]=temp_chromosome[i+1,c_val:]
    
    print("Cross-Overed Chromosome :", cross_chromosome)
    
    i=0 # index chromosome
    j=0 # 
    for x in flag:
        if(x):
            chromosome[i,:]=cross_chromosome[j,:]
            j+=1
        i+=1
    print("New Chromosomes :",chromosome)
    
    #calculating the total number of generations
    a,b= chromosome.shape[0],chromosome.shape[1]
    total_gen=a*b
    print("Total Generations :",total_gen)
    
    #mutation rate => pm
    pm=0.1
    no_of_mutations =int(np.round(pm*total_gen))
    print("No of Mutations : ",no_of_mutations)
    
    #calculating the Generation number
    gen_num=np.random.randint(0,total_gen-1,no_of_mutations)
    print("Generated Random Numbers : ",gen_num)
    
    # Genertaing a random number which can replace the selected chromosome to be mutated
    Replacing_num = np.random.randint(0,30,no_of_mutations)
    print("Numbers to be replaced : ",Replacing_num)

    for i in range(no_of_mutations):
        a=gen_num[i]
        row=a//4
        col=a%4
        chromosome[row,col]=Replacing_num[i]
    
    print("Chromosome after Mutation : ",chromosome)
    epoch+=1



Chromosome :  [[10  4  5  7]
 [18 20 17  5]
 [ 1 14 17 19]
 [18 25  1 23]
 [ 6 17 20 23]
 [ 3  6 18 10]]
Fitness Object : [10 84 69 64 93 49]
Fitness :  [ 0.09090909  0.01176471  0.01428571  0.01538462  0.0106383   0.02      ]
Total  0.162982424334
Probability :  [ 0.55778463  0.07218389  0.08765187  0.09439432  0.06527267  0.12271262]
Cumulative Probability :  [ 0.55778463  0.62996852  0.71762039  0.81201471  0.87728738  1.        ]
Random Numbers :  [ 0.26616127  0.93086892  0.49841018  0.84307762  0.71984636  0.94109399]
[[ 10.   4.   5.   7.]
 [  3.   6.  18.  10.]
 [ 10.   4.   5.   7.]
 [  6.  17.  20.  23.]
 [ 18.  25.   1.  23.]
 [  3.   6.  18.  10.]]
Updated chromosome :  [[ 10.   4.   5.   7.]
 [  3.   6.  18.  10.]
 [ 10.   4.   5.   7.]
 [  6.  17.  20.  23.]
 [ 18.  25.   1.  23.]
 [  3.   6.  18.  10.]]
[ True  True False False False  True]
cross chromosome : [[ 10.   4.   5.   7.]
 [  3.   6.  18.  10.]
 [  3.   6.  18.  10.]]
3
Cross Values :  [2 2 2]
[[ 10.   4.   5. 

0
Cross Values :  []
[]
Cross-Overed Chromosome : []
New Chromosomes : [[ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  1.]
 [ 3.  2.  5.  7.]]
Total Generations : 24
No of Mutations :  2
Generated Random Numbers :  [12  5]
Numbers to be replaced :  [9 9]
Chromosome after Mutation :  [[ 3.  2.  5.  7.]
 [ 3.  9.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 9.  2.  5.  7.]
 [ 3.  2.  5.  1.]
 [ 3.  2.  5.  7.]]
Fitness Object : [  1.  13.   1.   5.   7.   1.]
Fitness :  [ 0.5         0.07142857  0.5         0.16666667  0.125       0.5       ]
Total  1.8630952381
Probability :  [ 0.26837061  0.03833866  0.26837061  0.08945687  0.06709265  0.26837061]
Cumulative Probability :  [ 0.26837061  0.30670927  0.57507987  0.66453674  0.73162939  1.        ]
Random Numbers :  [ 0.52466606  0.45888542  0.68521092  0.10603267  0.93058385  0.08155561]
[[ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  1.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]
 [ 3.  2.  5.  7.]]
Updated 

Updated chromosome :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
[ True  True  True False  True False]
cross chromosome : [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
4
Cross Values :  [2 1 1 2]
[[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Cross-Overed Chromosome : [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
New Chromosomes : [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Total Generations : 24
No of Mutations :  2
Generated Random Numbers :  [ 0 22]
Numbers to be replaced :  [14  0]
Chromosome after Mutation :  [[ 14.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   0.  11.]]
Fitness Ob

cross chromosome : [[  3.   2.   4.  11.]]
1
Cross Values :  [2]
[[  3.   2.   4.  11.]]
Cross-Overed Chromosome : [[  3.   2.   4.  11.]]
New Chromosomes : [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.   6.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Total Generations : 24
No of Mutations :  2
Generated Random Numbers :  [19 15]
Numbers to be replaced :  [18 15]
Chromosome after Mutation :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.   6.]
 [  3.   2.   4.  15.]
 [  3.   2.   4.  18.]
 [  3.   2.   4.  11.]]
Fitness Object : [ 0.  0.  5.  4.  7.  0.]
Fitness :  [ 1.          1.          0.16666667  0.2         0.125       1.        ]
Total  3.49166666667
Probability :  [ 0.28639618  0.28639618  0.0477327   0.05727924  0.03579952  0.28639618]
Cumulative Probability :  [ 0.28639618  0.57279236  0.62052506  0.6778043   0.71360382  1.        ]
Random Numbers :  [ 0.23144916  0.86710325  0.88620004  0.97421673  0.68947689  0.08

Numbers to be replaced :  [26 24]
Chromosome after Mutation :  [[  3.   2.   3.  17.]
 [  3.   2.   4.  11.]
 [  3.   2.  24.  17.]
 [  3.   2.   3.  17.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Fitness Object : [  3.   0.  66.   3.   0.   0.]
Fitness :  [ 0.25        1.          0.01492537  0.25        1.          1.        ]
Total  3.51492537313
Probability :  [ 0.07112527  0.28450106  0.00424628  0.07112527  0.28450106  0.28450106]
Cumulative Probability :  [ 0.07112527  0.35562633  0.35987261  0.43099788  0.71549894  1.        ]
Random Numbers :  [ 0.27374415  0.29129744  0.50284585  0.01734099  0.95155531  0.94201442]
[[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   3.  17.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Updated chromosome :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   3.  17.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
[ True False False False False False]
cross chromosome : [[  3

Numbers to be replaced :  [16 11]
Chromosome after Mutation :  [[ 16.   2.   4.  11.]
 [ 11.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [ 10.   2.   4.  11.]]
Fitness Object : [ 13.   8.   0.   0.   0.   7.]
Fitness :  [ 0.07142857  0.11111111  1.          1.          1.          0.125     ]
Total  3.30753968254
Probability :  [ 0.02159568  0.03359328  0.30233953  0.30233953  0.30233953  0.03779244]
Cumulative Probability :  [ 0.02159568  0.05518896  0.35752849  0.65986803  0.96220756  1.        ]
Random Numbers :  [ 0.1905448   0.66455114  0.7544495   0.83020022  0.15504054  0.85725082]
[[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Updated chromosome :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
[False False  True  True  True  True]
cross chromosome : [[  3

Total  4.43333333333
Probability :  [ 0.22556391  0.07518797  0.02255639  0.22556391  0.22556391  0.22556391]
Cumulative Probability :  [ 0.22556391  0.30075188  0.32330827  0.54887218  0.77443609  1.        ]
Random Numbers :  [ 0.7395499   0.06078105  0.3980289   0.24523519  0.87236623  0.34005744]
[[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   3.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Updated chromosome :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   3.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
[False False False False False False]
cross chromosome : []
0
Cross Values :  []
[]
Cross-Overed Chromosome : []
New Chromosomes : [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   3.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Total Generations : 24
No of Mutations :  2
Generated Random Numbers :  [15 16]
Numbers to be replaced :  [16 12]
Chromosome aft

Numbers to be replaced :  [26  4]
Chromosome after Mutation :  [[  3.   2.   4.  11.]
 [  3.   2.   4.   4.]
 [ 26.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Fitness Object : [  0.   7.  23.   0.   0.   0.]
Fitness :  [ 1.          0.125       0.04166667  1.          1.          1.        ]
Total  4.16666666667
Probability :  [ 0.24  0.03  0.01  0.24  0.24  0.24]
Cumulative Probability :  [ 0.24  0.27  0.28  0.52  0.76  1.  ]
Random Numbers :  [ 0.55483421  0.97767287  0.6621024   0.25181301  0.47368689  0.66728802]
[[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.   4.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
Updated chromosome :  [[  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.   4.]
 [  3.   2.   4.  11.]
 [  3.   2.   4.  11.]]
[False False False False False False]
cross chromosome : []
0
Cross Values :  []
[]
Cross-Overed Chromosome : []
New Chromosomes : [[ 

In [73]:
chromosome[:,1]

array([ 7, 25,  6, 14, 13, 29])

In [95]:
chromosome

array([[24, 29, 17, 28],
       [25,  0, 19, 26],
       [12, 13,  9, 27],
       [ 4, 17, 18, 29],
       [25, 24,  6,  9],
       [22,  7, 23, 19]])