In [5]:
#numpy
import numpy as np
a=np.array([1,2,3,4]) # 1d array
print(a)
print(a.shape) # size of matrix
print(a.size)#total no. of elements
type(a)
b=np.array([[1,2,3],[10,20,30]])
print(b) # 2D matrix

# matrix index from 0 
print(b)
print(b[1,1]) # 2nd row 2 nd colm
print(b[1,:]) # 2nd row
print(b[:,2])# 3rd colum
print(b.sum()) # print sum of elemesnts
print(b.sum(axis=0))# print sum of columns
print(b.sum(axis=1))# print sum of rows
print(np.exp(b))# exponential of matrix
print(np.sqrt(b))# sqrt of b

#zeros matrix
c=np.zeros((3,4)) # 2D zero matrix elements are float
d=np.zeros((3,4),dtype=np.int16) # 2D zero matrix elements are float
e=np.ones((3,4),dtype=np.int16)

#arange function
f=np.arange(10,20,2)# arrange 10 to 19 by step 2
g=np.arange(12).reshape(4,3) # 2d matrix
h=np.arange(24).reshape(4,3,2) # 3d matrix
print(f)

#linspace
i=np.linspace(10,20,15) # line space 10 to 20 by total 15 points
print(i)

#basicoperations
a=np.array([20,30,40,50])
b=np.arange(4)
print("aray a-b", a-b)
print("aray a+b", a+b)
print("aray a**2", a**2)

# matrix product
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a*b) # element wise product
print(a.dot(b))# matrix product
print(np.dot(a,b))#matrix product

# random number
a=np.random.random((2,3)) # random no 2 row 3 coloumn

# shape manupulation
b=np.array([[1,2, 3],[4,5,6],[7,8,9],[10,11,12]])
b.reshape(4,3) # converted to 4 x 3 using row wise but orignal matrix unchnaged
b.resize(4,3) #converted to 4 x 3 using row wise but orignal matrix chnaged

## index start from 0
height=[2,3,4,5]
weight=[10,20,30,40]
np_height_m = np.array(height) * 0.0254

np_weight_kg = np.array(weight) * 0.453592

bmi = np_weight_kg / np_height_m ** 2 # devide
light=bmi<21 # logical array where bmi<21
print(light)

print(bmi[light])
print (bmi)

## Array addition & multiplication
print(np_baseball*conversion)
print(np_baseball+conversion)
## basic statistics
# a is vector
np.mean(a)
np.meadian(a)
np.corrcoef(a,b) # correlation of two vectors a and b
np.std(a)
np.sum()
np.sort()
np.round(2.345) #=>2 
np.round(2.345,2) # =>2.35
h=np.round(np.random.normal(1.75,0.2,5000),2)
w=np.round(np.random.normal(60.3,15,5000),2)# np.random.normal(mean,stdv,number of sample)
np_city=np.column_stack((h,w))


[1 2 3 4]
(4,)
4
[[ 1  2  3]
 [10 20 30]]
[[ 1  2  3]
 [10 20 30]]
20
[10 20 30]
[ 3 30]
66
[11 22 33]
[ 6 60]
[[  2.71828183e+00   7.38905610e+00   2.00855369e+01]
 [  2.20264658e+04   4.85165195e+08   1.06864746e+13]]
[[ 1.          1.41421356  1.73205081]
 [ 3.16227766  4.47213595  5.47722558]]
[10 12 14 16 18]
[ 10.          10.71428571  11.42857143  12.14285714  12.85714286
  13.57142857  14.28571429  15.          15.71428571  16.42857143
  17.14285714  17.85714286  18.57142857  19.28571429  20.        ]
aray a-b [20 29 38 47]
aray a+b [20 31 42 53]
aray a**2 [ 400  900 1600 2500]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[False False False False]
[]
[ 1757.67251535  1562.3755692   1318.25438651  1124.91040982]


NameError: name 'np_baseball' is not defined